In [1]:
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

diem      = np.load("/content/drive/MyDrive/python-learning/data/diem.npy")
thu_nhap  = np.load("/content/drive/MyDrive/python-learning/data/thu_nhap.npy")
du_no     = np.load("/content/drive/MyDrive/python-learning/data/du_no.npy")
nhom_no   = np.load("/content/drive/MyDrive/python-learning/data/nhom_no.npy")

Mounted at /content/drive


In [7]:
import numpy as np

du_lieu = np.column_stack((diem, thu_nhap, du_no))
print(du_lieu)

print(np.mean(du_lieu, axis = 0))
print(np.median(du_lieu, axis = 0))
print(np.std(du_lieu, axis = 0))
q1 =np.percentile(du_lieu, 25, axis = 0)
q3 = np.percentile(du_lieu, 75, axis = 0)
iqr = q3 - q1
print(q1)
print(q3)
print(iqr)
print(np.sum(np.isnan(du_lieu)))

outliers = [q1 - 1.5 * iqr, q3 + 1.5 * iqr]
print(outliers)
print(np.sum((du_lieu < outliers[0]) | (du_lieu > outliers[1])))


[[7.19737132e+02 3.19154039e+07 8.37412911e+07]
 [6.68938856e+02 5.21804717e+07 5.22839202e+07]
 [7.31815083e+02 9.98132865e+06 3.18215125e+08]
 ...
 [6.64772906e+02 2.76720099e+07 3.40113890e+08]
 [6.09950540e+02 1.50957086e+07 2.08364503e+07]
 [5.69376022e+02 2.67434983e+07 4.23960080e+07]]
[6.79908623e+02 2.30097359e+07 2.51089906e+08]
[6.81023772e+02 2.03741269e+07 2.55411012e+08]
[7.66600106e+01 1.19408150e+07 1.44659447e+08]
[6.23975408e+02 1.49148487e+07 1.19385555e+08]
[7.30942660e+02 2.78162826e+07 3.68259974e+08]
[1.06967253e+02 1.29014339e+07 2.48874418e+08]
0
[array([ 4.63524529e+02, -4.43730211e+06, -2.53926072e+08]), array([8.91393539e+02, 4.71684335e+07, 7.41571601e+08])]
27


In [10]:
import numpy as np
data = np.column_stack([diem, thu_nhap, du_no])

# Bước b — Thống kê mô tả đầy đủ cho mỗi cột
mean_data = np.mean(data, axis = 0)
median_data = np.median(data, axis = 0)
std_data = np.std(data, axis = 0)
min_data = np.min(data, axis = 0)
max_data = np.max(data, axis = 0)

# Bước c — Đếm NaN ở từng cột (không phải tổng)
sum_nan = np.sum(np.isnan(data), axis=0)

# Bước d — So sánh mean vs median từng cột
dif_mean_median = mean_data - median_data


# Bước e — Phát hiện outlier theo IQR cho TỪNG cột riêng, Đếm số outlier mỗi cột
q1 = np.percentile(data, 25, axis = 0)
q3 = np.percentile(data, 75, axis = 0)
iqr = q3- q1
lower = np.maximum(q1 - 1.5 * iqr,0)
upper = q3 + 1.5 * iqr

outlier = [lower, upper]

so_outlier =  np.sum(((data < lower) | (data > upper)), axis=0)
# Bước f — In báo cáo tổng hợp
print("=" * 60)
print(f"{'CHỈ SỐ':<15} {'DIEM':>10} {'THU_NHAP':>12} {'DU_NO':>12}")
print("=" * 60)
print(f"{'Trung bình cộng': <15} {mean_data[0] :>10,.0f} {mean_data[1]:>13,.0f} {mean_data[2]:>13,.0f}")
print(f"{'Trung vị': <16} {median_data[0] :>10,.0f} {median_data[1]:>13,.0f} {median_data[2]:>13,.0f}")
print(f"{'Độ lệch chuẩn': <18} {std_data[0] :>10,.0f} {std_data[1]:>13,.0f} {std_data[2]:>13,.0f}")
print(f"{'Giá trị bé nhất': <16} {min_data[0] :>10,.0f} {min_data[1]:>13,.0f} {min_data[2]:>13,.0f}")
print(f"{'Giá trị lớn nhất': <16} {max_data[0] :>9,.0f} {max_data[1]:>13,.0f} {max_data[2]:>13,.0f}")
print(f"{'Giá trị nan': <18} {sum_nan[0] :>9,.0f} {sum_nan[1]:>13,.0f} {sum_nan[2]:>13,.0f}")
print(f"{'So sánh mean vs median': <1} {dif_mean_median[0] :>3,.0f} {dif_mean_median[1]:>13,.0f} {dif_mean_median[2]:>13,.0f}")
print(f"{'Số lượng outlier': <15} {so_outlier[0] :>9,.0f} {so_outlier[1]:>13,.0f} {so_outlier[2]:>13,.0f}")

CHỈ SỐ                DIEM     THU_NHAP        DU_NO
Trung bình cộng        680    23,009,736   251,089,906
Trung vị               681    20,374,127   255,411,012
Độ lệch chuẩn           77    11,940,815   144,659,447
Giá trị bé nhất        421     5,215,092     2,469,990
Giá trị lớn nhất       850    74,902,782   499,706,863
Giá trị nan              0             0             0
So sánh mean vs median  -1     2,635,609    -4,321,106
Số lượng outlier         1            26             0


In [11]:
import numpy as np

data = np.column_stack((diem, thu_nhap, du_no))
mask_A = diem >= 650
mask_B = diem < 650

#Thống kê mô tả đầy đủ cho mỗi cột
mean_A = np.mean(data[mask_A], axis = 0)
median_A = np.median(data[mask_A], axis = 0)
std_A = np.std(data[mask_A], axis = 0)

mean_B = np.mean(data[mask_B], axis = 0)
median_B = np.median(data[mask_B], axis = 0)
std_B = np.std(data[mask_B], axis = 0)

print("=" * 60)
print(f"{'CHỈ SỐ':<15} {'DIEM':>10} {'THU_NHAP':>12} {'DU_NO':>12}")
print("=" * 60)
print(f"{'Trung bình cộng A': <15} {mean_A[0] :>10,.0f} {mean_A[1]:>13,.0f} {mean_A[2]:>13,.0f}")
print(f"{'Trung bình cộng B': <15} {mean_B[0] :>10,.0f} {mean_B[1]:>13,.0f} {mean_B[2]:>13,.0f}")
print(f"{'Trung vị A': <16} {median_A[0] :>12,.0f} {median_A[1]:>13,.0f} {median_A[2]:>13,.0f}")
print(f"{'Trung vị B': <16} {median_B[0] :>12,.0f} {median_B[1]:>13,.0f} {median_B[2]:>13,.0f}")
print(f"{'Độ lệch chuẩn A': <18} {std_A[0] :>12,.0f} {std_A[1]:>13,.0f} {std_A[2]:>13,.0f}")
print(f"{'Độ lệch chuẩn B': <18} {std_B[0] :>12,.0f} {std_B[1]:>13,.0f} {std_B[2]:>13,.0f}")
print("-" * 60)
print(f"{'Trung bình cộng A vs B': <15} {mean_A[0] - mean_B[0] :>6,.0f} {mean_A[1] - mean_B[1]:>13,.0f} {mean_A[2] - mean_B[2]:>13,.0f}")
print(f"{'Trung vị A vs B': <15} {median_A[0] - median_B[0] :>13,.0f} {median_A[1] - median_B[1]:>13,.0f} {median_A[2] - median_B[2]:>13,.0f}")
print(f"{'Độ lệch chuẩn A vs B': <15} {std_A[0] - std_B[0] :>8,.0f} {std_A[1] - std_B[1]:>13,.0f} {std_A[2] - std_B[2]:>13,.0f}")

CHỈ SỐ                DIEM     THU_NHAP        DU_NO
Trung bình cộng A        725    22,329,192   253,798,671
Trung bình cộng B        599    24,219,591   246,274,325
Trung vị A               716    19,738,710   266,031,829
Trung vị B               609    22,125,633   235,305,935
Độ lệch chuẩn A           51    11,419,499   142,818,860
Độ lệch chuẩn B           39    12,725,797   147,752,480
------------------------------------------------------------
Trung bình cộng A vs B    126    -1,890,399     7,524,346
Trung vị A vs B           108    -2,386,923    30,725,893
Độ lệch chuẩn A vs B       13    -1,306,298    -4,933,620


In [8]:
import numpy as np


data = np.column_stack((diem, thu_nhap, du_no))
nguong = [5, 10, 25, 50, 75, 90, 95, 99]

# Tính 1 dòng cho cột diem

p = np.percentile(diem, nguong)

# In theo format:
# P5  → xxx.x | Ý nghĩa: 5% khách có điểm dưới mức này
for i in range(len(nguong)):
    print(f"P{nguong[i]} - > {p[i]:.1f} | Ý nghĩa: {nguong[i]}% khách có điểm dưới mức này")

P5 - > 558.8 | Ý nghĩa: 5% khách có điểm dưới mức này
P10 - > 581.5 | Ý nghĩa: 10% khách có điểm dưới mức này
P25 - > 624.0 | Ý nghĩa: 25% khách có điểm dưới mức này
P50 - > 681.0 | Ý nghĩa: 50% khách có điểm dưới mức này
P75 - > 730.9 | Ý nghĩa: 75% khách có điểm dưới mức này
P90 - > 782.4 | Ý nghĩa: 90% khách có điểm dưới mức này
P95 - > 810.3 | Ý nghĩa: 95% khách có điểm dưới mức này
P99 - > 850.0 | Ý nghĩa: 99% khách có điểm dưới mức này
