In [2]:
import numpy as np

#from google.colab import drive
#drive.mount('/content/drive')

np.random.seed(42)
# Tạo ma trận điểm 5 học sinh × 4 môn (số nguyên 5-10)
diem = np.random.randint(5, 11, size=(5, 4))
print(diem)
'''(a) Tính điểm TB của từng môn (axis=0)
(b) Tính điểm TB của từng học sinh (axis=1)
(c) Chuẩn hóa: trừ điểm TB mỗi môn khỏi toàn bộ cột đó — 1 dòng, không vòng lặp
(d) Kiểm tra: np.mean(diem_chuan_hoa, axis=0) có ≈ 0 không?'''

#a
diem_tb_mon = np.mean(diem, axis = 0)
print(diem_tb_mon)
#b
diem_tb_hs = np.mean(diem, axis = 1)
print(diem_tb_hs)
#c
diem_chuan_hoa = diem - diem_tb_mon
print(diem_chuan_hoa)
#d
print(np.mean(diem_chuan_hoa, axis = 0))


Mounted at /content/drive
[[ 8  9  7  9]
 [ 9  6  7  7]
 [ 7  9  8  7]
 [10  9  6  8]
 [10 10  6  8]]
[8.8 8.6 6.8 7.8]
[8.25 7.25 7.75 8.25 8.5 ]
[[-0.8  0.4  0.2  1.2]
 [ 0.2 -2.6  0.2 -0.8]
 [-1.8  0.4  1.2 -0.8]
 [ 1.2  0.4 -0.8  0.2]
 [ 1.2  1.4 -0.8  0.2]]
[-7.10542736e-16  3.55271368e-16  1.77635684e-16  1.77635684e-16]


In [3]:
import numpy as np


diem      = np.load("/content/drive/MyDrive/python-learning/data/diem.npy")
thu_nhap  = np.load("/content/drive/MyDrive/python-learning/data/thu_nhap.npy")
du_no     = np.load("/content/drive/MyDrive/python-learning/data/du_no.npy")
nhom_no   = np.load("/content/drive/MyDrive/python-learning/data/nhom_no.npy")

print(diem.shape, thu_nhap.shape, du_no.shape, nhom_no.shape)

# Ghép thành ma trận (500, 3)
data = np.column_stack([diem, thu_nhap, du_no])
print(data.shape)   # phải ra (500, 3)

'''(a) Min-Max Normalization: (x - min) / (max - min)

Tính min và max theo từng cột — 1 dòng mỗi cái
Áp dụng công thức bằng broadcasting
Kiểm tra: min của mỗi cột chuẩn hóa = 0, max = 1

(b) Z-score Normalization: (x - mean) / std

Tương tự, dùng broadcasting
Kiểm tra: mean ≈ 0, std ≈ 1

(c) In bảng so sánh trước và sau chuẩn hóa — ví dụ 3 dòng đầu của mỗi cách.'''

#a
min_data = np.min(data, axis = 0)
max_data = np.max(data, axis = 0)

print(min_data)
print(max_data)

minmax = (data - min_data) / (max_data - min_data)
print(minmax)

#b
mean_data = np.mean(data, axis = 0)
std_data = np.std(data, axis = 0)

z_score = (data-mean_data)/std_data
print(z_score)

# Kiểm tra Min-Max
print("=== Min-Max ===")
print("Min mỗi cột:", np.min(minmax, axis=0))   # phải = [0, 0, 0]
print("Max mỗi cột:", np.max(minmax, axis=0))   # phải = [1, 1, 1]

# Kiểm tra Z-score
print("=== Z-score ===")
print("Mean mỗi cột:", np.mean(z_score, axis=0))  # phải ≈ [0, 0, 0]
print("Std mỗi cột: ", np.std(z_score, axis=0))   # phải ≈ [1, 1, 1]

(500,) (500,) (500,) (500,)
(500, 3)
[4.20698613e+02 5.21509173e+06 2.46999047e+06]
[8.50000000e+02 7.49027820e+07 4.99706863e+08]
[[0.69657012 0.38314245 0.16344584]
 [0.57824235 0.67394083 0.10018149]
 [0.72470409 0.06839424 0.63499944]
 ...
 [0.56853833 0.32225086 0.67904035]
 [0.44083698 0.14178425 0.03693704]
 [0.34632408 0.30892696 0.08029577]]
[[ 0.51954739  0.74581744 -1.15684539]
 [-0.14309635  2.44294346 -1.37430351]
 [ 0.67709956 -1.09108191  0.46402236]
 ...
 [-0.19743955  0.39044856  0.61540387]
 [-0.91257597 -0.66277111 -1.59169318]
 [-1.44185477  0.31268908 -1.44265654]]
=== Min-Max ===
Min mỗi cột: [0. 0. 0.]
Max mỗi cột: [1. 1. 1.]
=== Z-score ===
Mean mỗi cột: [ 4.51594317e-15 -6.59805544e-16 -4.75619544e-16]
Std mỗi cột:  [1. 1. 1.]


In [4]:
data = np.column_stack([diem, thu_nhap, du_no])
# Tạo mask cho 2 nhóm
du_dk  = diem >= 650   # đủ điều kiện
khong_dk = diem < 650  # không đủ điều kiện

print(f"Đủ ĐK:    {np.sum(du_dk)} khách")
print(f"Không ĐK: {np.sum(khong_dk)} khách")


#(a) Với mỗi nhóm, tính mean và std của cả 3 chỉ số (điểm, thu nhập, dư nợ)
#Nhóm đủ điều kiện
mean_du   = np.mean(data[du_dk], axis=0)   # shape (3,)
std_du   = np.std(data[du_dk], axis=0)


#Nhóm không đủ điều kiện
mean_khong = np.mean(data[khong_dk], axis=0)
std_khong   = np.std(data[khong_dk], axis=0)  # shape (3,)

#(b) In bảng
print(f"            Đủ điều kiện            Không đủ điều kiện")
print(f"Điểm TB:   {mean_du[0]}                    {mean_khong[0]}")
print(f"TN TB:     {mean_du[1]}                    {mean_khong[1]}")
print(f"DN TB:     {mean_du[2]}                    {mean_khong[2]}")


#(c)
print(f"Chênh lệch dư nợ TB: {mean_du[2]-mean_khong[2]}")

Đủ ĐK:    320 khách
Không ĐK: 180 khách
            Đủ điều kiện            Không đủ điều kiện
Điểm TB:   725.2757987086964                    599.2558674818483
TN TB:     22329192.143344667                    24219591.374026664
DN TB:     253798670.7726236                    246274325.10745162
Chênh lệch dư nợ TB: 7524345.665171981


In [6]:
'''(a) Tính Z-score cho từng cột của data — dùng lại z_score từ bài 1 hoặc tính lại
(b) Tạo mask outlier: hàng nào có ít nhất 1 cột có |z| > 3
(c) Đếm số hàng là outlier
(d) Lọc bỏ các hàng outlier — in shape của data còn lại'''

mean_data = np.mean(data, axis = 0)
std_data = np.std(data, axis = 0)

z_score = (data-mean_data)/std_data
print(z_score)

la_outlier = np.abs(z_score) > 3
mask = np.any(la_outlier, axis=1)

print(np.where(mask))
print(data[mask])
print(f"Số outlier:       {np.sum(mask)}")
print(f"Data còn lại:     {data[~mask].shape}")

[[ 0.51954739  0.74581744 -1.15684539]
 [-0.14309635  2.44294346 -1.37430351]
 [ 0.67709956 -1.09108191  0.46402236]
 ...
 [-0.19743955  0.39044856  0.61540387]
 [-0.91257597 -0.66277111 -1.59169318]
 [-1.44185477  0.31268908 -1.44265654]]
(array([ 83, 114, 154, 255, 262, 322, 347, 380, 409]),)
[[6.38538383e+02 6.25112430e+07 2.96475426e+08]
 [6.64611123e+02 6.82294295e+07 1.02920605e+08]
 [7.03445798e+02 7.27246144e+07 2.48587382e+08]
 [6.41261274e+02 7.49027820e+07 3.00805910e+08]
 [4.20698613e+02 7.22434936e+07 4.19930651e+08]
 [6.14542345e+02 6.33990617e+07 2.78891709e+08]
 [5.67402898e+02 6.85559411e+07 3.11792844e+08]
 [6.12822253e+02 7.10558518e+07 4.04596415e+07]
 [7.21155107e+02 5.92417993e+07 5.28323421e+07]]
Số outlier:       9
Data còn lại:     (491, 3)
